# Generated by Django 5.2.6 on 2025-10-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=45, unique=True)),
                ('nombre_empresa', models.CharField(max_length=250, unique=True)),
                ('categoria_empresa', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('turismo', 'Turismo'), ('educacion', 'Educación'), ('salud', 'Salud')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'db_table_comment': ' ',
            },
        ),
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id_influencer', models.AutoField(primary_key=True, serialize=False)),
                ('rut_influencer', models.CharField(max_length=45, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_pat', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_mat', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('turismo', 'Turismo'), ('educacion', 'Educación'), ('salud', 'Salud')], max_length=20, null=True)),
                ('seguidores', models.BigIntegerField(blank=True, null=True)),
                ('prom_views', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ('Influencer',),
                'verbose_name_plural': ('Influencers',),
                'db_table': 'influencers',
            },
        ),
        migrations.CreateModel(
            name='Campanas',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='almaUnionApp.empresas')),
            ],
            options={
                'verbose_name': ('Campaña',),
                'verbose_name_plural': ('Campañas',),
                'db_table': 'campanas',
            },
        ),
        migrations.CreateModel(
            name='Colaboraciones',
            fields=[
                ('id_colaboracion', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('pago_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creacion_add', models.DateTimeField(blank=True, null=True)),
                ('id_campana', models.ForeignKey(db_column='id_campana', on_delete=django.db.models.deletion.PROTECT, related_name='colaboraciones', to='almaUnionApp.campanas')),
                ('id_influencer', models.ForeignKey(db_column='id_influencer', on_delete=django.db.models.deletion.PROTECT, related_name='colaboraciones', to='almaUnionApp.influencers')),
            ],
            options={
                'verbose_name': ('Colaboracion',),
                'verbose_name_plural': ('Colaboraciones',),
                'db_table': 'colaboraciones',
            },
        ),
        migrations.CreateModel(
            name='MetricasH',
            fields=[
                ('id_metrica', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('x', 'X/ Twitter')], max_length=20, null=True)),
                ('fecha_analisis', models.DateField(blank=True, null=True)),
                ('seguidores', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comentarios', models.BigIntegerField(blank=True, null=True)),
                ('id_influencer', models.ForeignKey(db_column='id_influencer', on_delete=django.db.models.deletion.PROTECT, related_name='metricas', to='almaUnionApp.influencers')),
            ],
            options={
                'verbose_name': ('Metrica Historica',),
                'verbose_name_plural': ('Metricas Historicas',),
                'db_table': 'metricas_h',
            },
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id_red_social', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('x', 'X/ Twitter')], max_length=20)),
                ('canal', models.URLField(blank=True, max_length=150)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('seguidores', models.BigIntegerField(blank=True, null=True)),
                ('vistas', models.BigIntegerField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redes_sociales', to='almaUnionApp.empresas')),
                ('id_influencer', models.ForeignKey(blank=True, db_column='id_influencer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redes_sociales', to='almaUnionApp.influencers')),
            ],
            options={
                'verbose_name': ('Red Social',),
                'verbose_name_plural': ('Redes Sociales',),
                'db_table': 'redes_sociales',
                'db_table_comment': ' ',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('influencer', 'Influencer'), ('empresa', 'Empresa')], max_length=15)),
                ('verificado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='almaUnionApp.empresas')),
                ('id_influencer', models.ForeignKey(blank=True, db_column='id_influencer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='almaUnionApp.influencers')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='campanas',
            index=models.Index(fields=['id_empresa'], name='campanas_id_empr_fc4433_idx'),
        ),
        migrations.AddIndex(
            model_name='colaboraciones',
            index=models.Index(fields=['id_influencer'], name='colaboracio_id_infl_8a0af4_idx'),
        ),
        migrations.AddIndex(
            model_name='colaboraciones',
            index=models.Index(fields=['id_campana'], name='colaboracio_id_camp_f8c341_idx'),
        ),
        migrations.AddIndex(
            model_name='metricash',
            index=models.Index(fields=['id_influencer'], name='metricas_h_id_infl_091ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='metricash',
            index=models.Index(fields=['plataforma'], name='metricas_h_platafo_bb94b0_idx'),
        ),
        migrations.AddIndex(
            model_name='metricash',
            index=models.Index(fields=['fecha_analisis'], name='metricas_h_fecha_a_bfee8d_idx'),
        ),
        migrations.AddIndex(
            model_name='redessociales',
            index=models.Index(fields=['id_influencer'], name='redes_socia_id_infl_e20607_idx'),
        ),
        migrations.AddIndex(
            model_name='redessociales',
            index=models.Index(fields=['id_empresa'], name='redes_socia_id_empr_e2add1_idx'),
        ),
        migrations.AddIndex(
            model_name='redessociales',
            index=models.Index(fields=['plataforma'], name='redes_socia_platafo_78adb3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
    ]
