# Generated by Django 5.2.6 on 2025-10-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaUnionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campanas',
            name='campanas_id_empr_fc4433_idx',
        ),
        migrations.RemoveIndex(
            model_name='colaboraciones',
            name='colaboracio_id_infl_8a0af4_idx',
        ),
        migrations.RemoveIndex(
            model_name='colaboraciones',
            name='colaboracio_id_camp_f8c341_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricash',
            name='metricas_h_id_infl_091ddb_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricash',
            name='metricas_h_platafo_bb94b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='metricash',
            name='metricas_h_fecha_a_bfee8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='redessociales',
            name='redes_socia_id_infl_e20607_idx',
        ),
        migrations.RemoveIndex(
            model_name='redessociales',
            name='redes_socia_id_empr_e2add1_idx',
        ),
        migrations.RemoveIndex(
            model_name='redessociales',
            name='redes_socia_platafo_78adb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuarios',
            name='usuarios_email_0ff7b3_idx',
        ),
        migrations.RenameField(
            model_name='influencers',
            old_name='categoria',
            new_name='categoria_influencer',
        ),
        migrations.RemoveField(
            model_name='campanas',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='colaboraciones',
            name='creacion_add',
        ),
        migrations.RemoveField(
            model_name='colaboraciones',
            name='id_campana',
        ),
        migrations.RemoveField(
            model_name='colaboraciones',
            name='id_influencer',
        ),
        migrations.RemoveField(
            model_name='metricash',
            name='id_influencer',
        ),
        migrations.RemoveField(
            model_name='redessociales',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='redessociales',
            name='id_influencer',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_influencer',
        ),
        migrations.AddField(
            model_name='campanas',
            name='id_empresa_campanas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboraciones',
            name='id_campana_colaboracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboraciones',
            name='id_empresa_colaboracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaboraciones',
            name='id_influencer_colaboracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricash',
            name='id_empresa_metricas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricash',
            name='id_influencer_metricas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redessociales',
            name='id_empresa_redes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redessociales',
            name='id_influencer_redes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_empresa_usuarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_influencer_usuarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='almaUnion.static.img.empresa'),
        ),
    ]
