# Generated by Django 5.2.6 on 2025-10-20 06:30

import almaUnionApp.validators.validatorValidarRut
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaUnionApp', '0002_remove_campanas_campanas_id_empr_fc4433_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanas',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='colaboraciones',
            options={'verbose_name': 'Colaboracion', 'verbose_name_plural': 'Colaboraciones'},
        ),
        migrations.AlterModelOptions(
            name='influencers',
            options={'verbose_name': 'Influencer', 'verbose_name_plural': 'Influencers'},
        ),
        migrations.AlterModelOptions(
            name='metricash',
            options={'verbose_name': 'Metrica Historica', 'verbose_name_plural': 'Metricas Historicas'},
        ),
        migrations.AlterModelOptions(
            name='redessociales',
            options={'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='metricash',
            name='nombre_metrica',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metricash',
            name='video',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='metricash',
            name='vistas',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='rut_influencer',
            field=models.CharField(max_length=45, unique=True, validators=[almaUnionApp.validators.validatorValidarRut.validar_rut]),
        ),
        migrations.AlterField(
            model_name='metricash',
            name='comentarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metricash',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metricash',
            name='seguidores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
