# Generated by Django 5.2.5 on 2025-11-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaUnionApp', '0003_alter_campanas_options_alter_colaboraciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanas',
            name='categoria',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('turismo', 'Turismo'), ('educacion', 'Educación'), ('salud', 'Salud')], max_length=20, null=True),
        ),
    ]
